// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tak/proto/corpus_entry.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CorpusEntry struct {
	Day                  string   `protobuf:"bytes,1,opt,name=day" json:"day,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Ply                  int32    `protobuf:"varint,3,opt,name=ply" json:"ply,omitempty"`
	Tps                  string   `protobuf:"bytes,4,opt,name=tps" json:"tps,omitempty"`
	Move                 string   `protobuf:"bytes,5,opt,name=move" json:"move,omitempty"`
	Value                float32  `protobuf:"fixed32,6,opt,name=value" json:"value,omitempty"`
	Plies                int32    `protobuf:"varint,7,opt,name=plies" json:"plies,omitempty"`
	Features             []int64  `protobuf:"varint,8,rep,packed,name=features" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CorpusEntry) Reset()         { *m = CorpusEntry{} }
func (m *CorpusEntry) String() string { return proto.CompactTextString(m) }
func (*CorpusEntry) ProtoMessage()    {}
func (*CorpusEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_corpus_entry_252366702f1d31fd, []int{0}
}
func (m *CorpusEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CorpusEntry.Unmarshal(m, b)
}
func (m *CorpusEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CorpusEntry.Marshal(b, m, deterministic)
}
func (dst *CorpusEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CorpusEntry.Merge(dst, src)
}
func (m *CorpusEntry) XXX_Size() int {
	return xxx_messageInfo_CorpusEntry.Size(m)
}
func (m *CorpusEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CorpusEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CorpusEntry proto.InternalMessageInfo

func (m *CorpusEntry) GetDay() string {
	if m != nil {
		return m.Day
	}
	return ""
}

func (m *CorpusEntry) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CorpusEntry) GetPly() int32 {
	if m != nil {
		return m.Ply
	}
	return 0
}

func (m *CorpusEntry) GetTps() string {
	if m != nil {
		return m.Tps
	}
	return ""
}

func (m *CorpusEntry) GetMove() string {
	if m != nil {
		return m.Move
	}
	return ""
}

func (m *CorpusEntry) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *CorpusEntry) GetPlies() int32 {
	if m != nil {
		return m.Plies
	}
	return 0
}

func (m *CorpusEntry) GetFeatures() []int64 {
	if m != nil {
		return m.Features
	}
	return nil
}

func init() {
	proto.RegisterType((*CorpusEntry)(nil), "tak.proto.CorpusEntry")
}

func init() {
	proto.RegisterFile("tak/proto/corpus_entry.proto", fileDescriptor_corpus_entry_252366702f1d31fd)
}

var fileDescriptor_corpus_entry_252366702f1d31fd = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0xb1, 0xaa, 0xc3, 0x20,
	0x18, 0x46, 0x51, 0x93, 0xdc, 0xc4, 0x0b, 0x97, 0x8b, 0x74, 0xf8, 0x29, 0x1d, 0xa4, 0x93, 0x53,
	0x33, 0xf4, 0x0d, 0x5a, 0xfa, 0x02, 0x8e, 0x5d, 0x8a, 0x69, 0x2c, 0x84, 0xa4, 0x55, 0xd4, 0x04,
	0xf2, 0x54, 0x7d, 0xc5, 0xa2, 0x42, 0xb7, 0xf3, 0x1d, 0x8e, 0xf2, 0xd3, 0x5d, 0x50, 0x63, 0x6b,
	0x9d, 0x09, 0xa6, 0xbd, 0x1b, 0x67, 0x67, 0x7f, 0xd3, 0xaf, 0xe0, 0xd6, 0x43, 0x52, 0xac, 0x09,
	0x6a, 0xcc, 0xb8, 0x7f, 0x23, 0xfa, 0x7b, 0x4e, 0xc5, 0x25, 0x06, 0xec, 0x9f, 0x92, 0x5e, 0xad,
	0x80, 0x38, 0x12, 0x8d, 0x8c, 0xc8, 0xfe, 0x28, 0x1e, 0x7a, 0xc0, 0x1c, 0x89, 0x52, 0xe2, 0xa1,
	0x8f, 0x85, 0x9d, 0x56, 0x20, 0x49, 0x44, 0x8c, 0x26, 0x58, 0x0f, 0x45, 0x7e, 0x13, 0xac, 0x67,
	0x8c, 0x16, 0x4f, 0xb3, 0x68, 0x28, 0x93, 0x4a, 0xcc, 0x36, 0xb4, 0x5c, 0xd4, 0x34, 0x6b, 0xa8,
	0x38, 0x12, 0x58, 0xe6, 0x11, 0xad, 0x9d, 0x06, 0xed, 0xe1, 0x27, 0xfd, 0x97, 0x07, 0xdb, 0xd2,
	0xfa, 0xa1, 0x55, 0x98, 0x9d, 0xf6, 0x50, 0x73, 0x22, 0x88, 0xfc, 0xee, 0x53, 0x71, 0xc5, 0xb6,
	0xeb, 0xaa, 0x74, 0xfe, 0xf1, 0x13, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xdf, 0xf5, 0x03, 0xe9, 0x00,
	0x00, 0x00,
}
