// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tak/proto/corpus_entry.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CorpusEntry_InTak int32

const (
	CorpusEntry_UNSET      CorpusEntry_InTak = 0
	CorpusEntry_NOT_IN_TAK CorpusEntry_InTak = 1
	CorpusEntry_IN_TAK     CorpusEntry_InTak = 2
)

var CorpusEntry_InTak_name = map[int32]string{
	0: "UNSET",
	1: "NOT_IN_TAK",
	2: "IN_TAK",
}
var CorpusEntry_InTak_value = map[string]int32{
	"UNSET":      0,
	"NOT_IN_TAK": 1,
	"IN_TAK":     2,
}

func (x CorpusEntry_InTak) String() string {
	return proto.EnumName(CorpusEntry_InTak_name, int32(x))
}
func (CorpusEntry_InTak) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_corpus_entry_f1dff66f2769f234, []int{0, 0}
}

type CorpusEntry struct {
	Day                  string            `protobuf:"bytes,1,opt,name=day" json:"day,omitempty"`
	Id                   int32             `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Ply                  int32             `protobuf:"varint,3,opt,name=ply" json:"ply,omitempty"`
	Tps                  string            `protobuf:"bytes,4,opt,name=tps" json:"tps,omitempty"`
	Move                 string            `protobuf:"bytes,5,opt,name=move" json:"move,omitempty"`
	Value                float32           `protobuf:"fixed32,6,opt,name=value" json:"value,omitempty"`
	Plies                int32             `protobuf:"varint,7,opt,name=plies" json:"plies,omitempty"`
	Features             []int64           `protobuf:"varint,8,rep,packed,name=features" json:"features,omitempty"`
	InTak                CorpusEntry_InTak `protobuf:"varint,9,opt,name=in_tak,json=inTak,enum=tak.proto.CorpusEntry_InTak" json:"in_tak,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CorpusEntry) Reset()         { *m = CorpusEntry{} }
func (m *CorpusEntry) String() string { return proto.CompactTextString(m) }
func (*CorpusEntry) ProtoMessage()    {}
func (*CorpusEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_corpus_entry_f1dff66f2769f234, []int{0}
}
func (m *CorpusEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CorpusEntry.Unmarshal(m, b)
}
func (m *CorpusEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CorpusEntry.Marshal(b, m, deterministic)
}
func (dst *CorpusEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CorpusEntry.Merge(dst, src)
}
func (m *CorpusEntry) XXX_Size() int {
	return xxx_messageInfo_CorpusEntry.Size(m)
}
func (m *CorpusEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CorpusEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CorpusEntry proto.InternalMessageInfo

func (m *CorpusEntry) GetDay() string {
	if m != nil {
		return m.Day
	}
	return ""
}

func (m *CorpusEntry) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CorpusEntry) GetPly() int32 {
	if m != nil {
		return m.Ply
	}
	return 0
}

func (m *CorpusEntry) GetTps() string {
	if m != nil {
		return m.Tps
	}
	return ""
}

func (m *CorpusEntry) GetMove() string {
	if m != nil {
		return m.Move
	}
	return ""
}

func (m *CorpusEntry) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *CorpusEntry) GetPlies() int32 {
	if m != nil {
		return m.Plies
	}
	return 0
}

func (m *CorpusEntry) GetFeatures() []int64 {
	if m != nil {
		return m.Features
	}
	return nil
}

func (m *CorpusEntry) GetInTak() CorpusEntry_InTak {
	if m != nil {
		return m.InTak
	}
	return CorpusEntry_UNSET
}

func init() {
	proto.RegisterType((*CorpusEntry)(nil), "tak.proto.CorpusEntry")
	proto.RegisterEnum("tak.proto.CorpusEntry_InTak", CorpusEntry_InTak_name, CorpusEntry_InTak_value)
}

func init() {
	proto.RegisterFile("tak/proto/corpus_entry.proto", fileDescriptor_corpus_entry_f1dff66f2769f234)
}

var fileDescriptor_corpus_entry_f1dff66f2769f234 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x6a, 0xb4, 0x30,
	0x14, 0x85, 0xff, 0x44, 0xe3, 0x3f, 0xde, 0x82, 0xc8, 0xa5, 0x8b, 0x50, 0x66, 0x21, 0xb3, 0x72,
	0xe5, 0x40, 0xe7, 0x09, 0xda, 0x32, 0x8b, 0xa1, 0x60, 0xc1, 0xda, 0x4d, 0x37, 0x92, 0xa9, 0x29,
	0x04, 0xad, 0x06, 0x13, 0x07, 0x7c, 0x8f, 0x3e, 0x70, 0x49, 0x2c, 0x43, 0x57, 0xf9, 0xce, 0xc7,
	0xc9, 0x85, 0x03, 0x5b, 0x2b, 0xba, 0xbd, 0x9e, 0x46, 0x3b, 0xee, 0x3f, 0xc6, 0x49, 0xcf, 0xa6,
	0x91, 0x83, 0x9d, 0x96, 0xc2, 0x2b, 0x8c, 0xad, 0xe8, 0x56, 0xdc, 0x7d, 0x53, 0xb8, 0x79, 0xf2,
	0x8d, 0xa3, 0x2b, 0x60, 0x0a, 0x41, 0x2b, 0x16, 0x4e, 0x32, 0x92, 0xc7, 0x95, 0x43, 0x4c, 0x80,
	0xaa, 0x96, 0xd3, 0x8c, 0xe4, 0xac, 0xa2, 0xaa, 0x75, 0x0d, 0xdd, 0x2f, 0x3c, 0xf0, 0xc2, 0xa1,
	0x33, 0x56, 0x1b, 0x1e, 0xae, 0x7f, 0xac, 0x36, 0x88, 0x10, 0x7e, 0x8d, 0x17, 0xc9, 0x99, 0x57,
	0x9e, 0xf1, 0x16, 0xd8, 0x45, 0xf4, 0xb3, 0xe4, 0x51, 0x46, 0x72, 0x5a, 0xad, 0xc1, 0x59, 0xdd,
	0x2b, 0x69, 0xf8, 0x7f, 0x7f, 0x6f, 0x0d, 0x78, 0x07, 0x9b, 0x4f, 0x29, 0xec, 0x3c, 0x49, 0xc3,
	0x37, 0x59, 0x90, 0x07, 0xd5, 0x35, 0xe3, 0x01, 0x22, 0x35, 0x34, 0x56, 0x74, 0x3c, 0xce, 0x48,
	0x9e, 0xdc, 0x6f, 0x8b, 0xeb, 0x9a, 0xe2, 0xcf, 0x92, 0xe2, 0x34, 0xd4, 0xa2, 0xab, 0x98, 0x72,
	0xcf, 0xae, 0x00, 0xe6, 0x33, 0xc6, 0xc0, 0xde, 0xca, 0xd7, 0x63, 0x9d, 0xfe, 0xc3, 0x04, 0xa0,
	0x7c, 0xa9, 0x9b, 0x53, 0xd9, 0xd4, 0x0f, 0xcf, 0x29, 0x41, 0x80, 0xe8, 0x97, 0xe9, 0x63, 0xf8,
	0x4e, 0xf5, 0xf9, 0x1c, 0xf9, 0xab, 0x87, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x38, 0xf4, 0xe2,
	0xf3, 0x4e, 0x01, 0x00, 0x00,
}
