// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tak/proto/model.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ModelDef struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	Layers               int32    `protobuf:"varint,2,opt,name=layers" json:"layers,omitempty"`
	Kernel               int32    `protobuf:"varint,3,opt,name=kernel" json:"kernel,omitempty"`
	Filters              int32    `protobuf:"varint,4,opt,name=filters" json:"filters,omitempty"`
	Hidden               int32    `protobuf:"varint,5,opt,name=hidden" json:"hidden,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelDef) Reset()         { *m = ModelDef{} }
func (m *ModelDef) String() string { return proto.CompactTextString(m) }
func (*ModelDef) ProtoMessage()    {}
func (*ModelDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_4dc4fc4b7143678c, []int{0}
}
func (m *ModelDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelDef.Unmarshal(m, b)
}
func (m *ModelDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelDef.Marshal(b, m, deterministic)
}
func (dst *ModelDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelDef.Merge(dst, src)
}
func (m *ModelDef) XXX_Size() int {
	return xxx_messageInfo_ModelDef.Size(m)
}
func (m *ModelDef) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelDef.DiscardUnknown(m)
}

var xxx_messageInfo_ModelDef proto.InternalMessageInfo

func (m *ModelDef) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ModelDef) GetLayers() int32 {
	if m != nil {
		return m.Layers
	}
	return 0
}

func (m *ModelDef) GetKernel() int32 {
	if m != nil {
		return m.Kernel
	}
	return 0
}

func (m *ModelDef) GetFilters() int32 {
	if m != nil {
		return m.Filters
	}
	return 0
}

func (m *ModelDef) GetHidden() int32 {
	if m != nil {
		return m.Hidden
	}
	return 0
}

func init() {
	proto.RegisterType((*ModelDef)(nil), "tak.proto.ModelDef")
}

func init() { proto.RegisterFile("tak/proto/model.proto", fileDescriptor_model_4dc4fc4b7143678c) }

var fileDescriptor_model_4dc4fc4b7143678c = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x49, 0xcc, 0xd6,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0xcd, 0x4f, 0x49, 0xcd, 0xd1, 0x03, 0xb3, 0x85, 0x38,
	0x4b, 0x12, 0xb3, 0x21, 0x4c, 0xa5, 0x06, 0x46, 0x2e, 0x0e, 0x5f, 0x90, 0x94, 0x4b, 0x6a, 0x9a,
	0x90, 0x10, 0x17, 0x4b, 0x71, 0x66, 0x55, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x98,
	0x2d, 0x24, 0xc6, 0xc5, 0x96, 0x93, 0x58, 0x99, 0x5a, 0x54, 0x2c, 0xc1, 0x04, 0x16, 0x85, 0xf2,
	0x40, 0xe2, 0xd9, 0xa9, 0x45, 0x79, 0xa9, 0x39, 0x12, 0xcc, 0x10, 0x71, 0x08, 0x4f, 0x48, 0x82,
	0x8b, 0x3d, 0x2d, 0x33, 0xa7, 0x04, 0xa4, 0x81, 0x05, 0x2c, 0x01, 0xe3, 0x82, 0x74, 0x64, 0x64,
	0xa6, 0xa4, 0xa4, 0xe6, 0x49, 0xb0, 0x42, 0x74, 0x40, 0x78, 0x4e, 0x2c, 0x51, 0x4c, 0x05, 0x49,
	0x49, 0x6c, 0x60, 0xf7, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x29, 0xe4, 0x1e, 0x56, 0xb3,
	0x00, 0x00, 0x00,
}
