// Code generated by "stringer -type=MoveType"; DO NOT EDIT.

package tak

import "strconv"

const (
	_MoveType_name_0 = "PassPlaceFlatPlaceStandingPlaceCapstoneSlideLeftSlideRightSlideUpSlideDown"
	_MoveType_name_1 = "TypeMask"
)

var (
	_MoveType_index_0 = [...]uint8{0, 4, 13, 26, 39, 48, 58, 65, 74}
)

func (i MoveType) String() string {
	switch {
	case 1 <= i && i <= 8:
		i -= 1
		return _MoveType_name_0[_MoveType_index_0[i]:_MoveType_index_0[i+1]]
	case i == 15:
		return _MoveType_name_1
	default:
		return "MoveType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
