#!/usr/bin/env python
import argparse
import yaml
import os.path
from tak.alphazero import trainer


def main():
    parser = argparse.ArgumentParser(description="Resume an alphazero run")
    parser.add_argument("run_dir", type=str)

    args = parser.parse_args()

    with open(os.path.join(args.run_dir, "run.yaml"), "r") as fh:
        config = yaml.unsafe_load(fh)

    train = trainer.TrainingRun(config=config)
    train.run()


if __name__ == "__main__":
    main()
