// Code generated by protoc-gen-go. DO NOT EDIT.
// source: corpus_entry.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	corpus_entry.proto
	model.proto

It has these top-level messages:
	CorpusEntry
	ModelDef
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CorpusEntry struct {
	Day      string  `protobuf:"bytes,1,opt,name=day" json:"day,omitempty"`
	Id       int32   `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Ply      int32   `protobuf:"varint,3,opt,name=ply" json:"ply,omitempty"`
	Tps      string  `protobuf:"bytes,4,opt,name=tps" json:"tps,omitempty"`
	Move     string  `protobuf:"bytes,5,opt,name=move" json:"move,omitempty"`
	Value    float32 `protobuf:"fixed32,6,opt,name=value" json:"value,omitempty"`
	Plies    int32   `protobuf:"varint,7,opt,name=plies" json:"plies,omitempty"`
	Features []int64 `protobuf:"varint,8,rep,packed,name=features" json:"features,omitempty"`
}

func (m *CorpusEntry) Reset()                    { *m = CorpusEntry{} }
func (m *CorpusEntry) String() string            { return proto.CompactTextString(m) }
func (*CorpusEntry) ProtoMessage()               {}
func (*CorpusEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CorpusEntry) GetDay() string {
	if m != nil {
		return m.Day
	}
	return ""
}

func (m *CorpusEntry) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CorpusEntry) GetPly() int32 {
	if m != nil {
		return m.Ply
	}
	return 0
}

func (m *CorpusEntry) GetTps() string {
	if m != nil {
		return m.Tps
	}
	return ""
}

func (m *CorpusEntry) GetMove() string {
	if m != nil {
		return m.Move
	}
	return ""
}

func (m *CorpusEntry) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *CorpusEntry) GetPlies() int32 {
	if m != nil {
		return m.Plies
	}
	return 0
}

func (m *CorpusEntry) GetFeatures() []int64 {
	if m != nil {
		return m.Features
	}
	return nil
}

func init() {
	proto.RegisterType((*CorpusEntry)(nil), "tak.proto.CorpusEntry")
}

func init() { proto.RegisterFile("corpus_entry.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0xb1, 0xaa, 0xc3, 0x20,
	0x14, 0x86, 0x51, 0x93, 0xdc, 0xc4, 0x0b, 0x97, 0xcb, 0xa1, 0xc3, 0xa1, 0x93, 0x74, 0x72, 0xea,
	0xd2, 0x37, 0x68, 0xe9, 0x0b, 0x38, 0x76, 0x29, 0xa6, 0xb1, 0x10, 0x9a, 0x56, 0x51, 0x13, 0xc8,
	0x53, 0xf5, 0x15, 0x8b, 0x0a, 0xdd, 0xbe, 0xff, 0xe3, 0x53, 0x0e, 0x87, 0x9b, 0xf5, 0x6e, 0x0e,
	0x57, 0xf3, 0x8a, 0x7e, 0xdd, 0x3b, 0x6f, 0xa3, 0x85, 0x2e, 0xea, 0x47, 0xc1, 0xdd, 0x9b, 0xf0,
	0xdf, 0x53, 0x2e, 0xce, 0x29, 0x80, 0x7f, 0xce, 0x06, 0xbd, 0x22, 0x11, 0x44, 0x76, 0x2a, 0x21,
	0xfc, 0x71, 0x3a, 0x0e, 0x48, 0x05, 0x91, 0xb5, 0xa2, 0xe3, 0x90, 0x0a, 0x37, 0xad, 0xc8, 0xb2,
	0x48, 0x98, 0x4c, 0x74, 0x01, 0xab, 0xf2, 0x26, 0xba, 0x00, 0xc0, 0xab, 0xa7, 0x5d, 0x0c, 0xd6,
	0x59, 0x65, 0x86, 0x0d, 0xaf, 0x17, 0x3d, 0xcd, 0x06, 0x1b, 0x41, 0x24, 0x55, 0x65, 0x24, 0xeb,
	0xa6, 0xd1, 0x04, 0xfc, 0xc9, 0xff, 0x95, 0x01, 0x5b, 0xde, 0xde, 0x8d, 0x8e, 0xb3, 0x37, 0x01,
	0x5b, 0xc1, 0x24, 0x53, 0xdf, 0x7d, 0xac, 0x2e, 0xd4, 0xf5, 0x7d, 0x93, 0xcf, 0x3f, 0x7c, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x42, 0xef, 0xc6, 0x0b, 0xdf, 0x00, 0x00, 0x00,
}
