# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tak.proto import analysis_pb2 as tak_dot_proto_dot_analysis__pb2


class AnalysisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Evaluate = channel.unary_unary(
                '/tak.proto.Analysis/Evaluate',
                request_serializer=tak_dot_proto_dot_analysis__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=tak_dot_proto_dot_analysis__pb2.EvaluateResponse.FromString,
                )


class AnalysisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Evaluate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=tak_dot_proto_dot_analysis__pb2.EvaluateRequest.FromString,
                    response_serializer=tak_dot_proto_dot_analysis__pb2.EvaluateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tak.proto.Analysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Analysis(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tak.proto.Analysis/Evaluate',
            tak_dot_proto_dot_analysis__pb2.EvaluateRequest.SerializeToString,
            tak_dot_proto_dot_analysis__pb2.EvaluateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
