# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tak/proto/corpus_entry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctak/proto/corpus_entry.proto\x12\ttak.proto\"\xdc\x01\n\x0b\x43orpusEntry\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0b\n\x03ply\x18\x03 \x01(\x05\x12\x0b\n\x03tps\x18\x04 \x01(\t\x12\x0c\n\x04move\x18\x05 \x01(\t\x12\r\n\x05value\x18\x06 \x01(\x02\x12\r\n\x05plies\x18\x07 \x01(\x05\x12\x10\n\x08\x66\x65\x61tures\x18\x08 \x03(\x03\x12,\n\x06in_tak\x18\t \x01(\x0e\x32\x1c.tak.proto.CorpusEntry.InTak\".\n\x05InTak\x12\t\n\x05UNSET\x10\x00\x12\x0e\n\nNOT_IN_TAK\x10\x01\x12\n\n\x06IN_TAK\x10\x02\x42!Z\x1fgithub.com/nelhage/taktician/pbb\x06proto3')



_CORPUSENTRY = DESCRIPTOR.message_types_by_name['CorpusEntry']
_CORPUSENTRY_INTAK = _CORPUSENTRY.enum_types_by_name['InTak']
CorpusEntry = _reflection.GeneratedProtocolMessageType('CorpusEntry', (_message.Message,), {
  'DESCRIPTOR' : _CORPUSENTRY,
  '__module__' : 'tak.proto.corpus_entry_pb2'
  # @@protoc_insertion_point(class_scope:tak.proto.CorpusEntry)
  })
_sym_db.RegisterMessage(CorpusEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037github.com/nelhage/taktician/pb'
  _CORPUSENTRY._serialized_start=44
  _CORPUSENTRY._serialized_end=264
  _CORPUSENTRY_INTAK._serialized_start=218
  _CORPUSENTRY_INTAK._serialized_end=264
# @@protoc_insertion_point(module_scope)
