# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from tak.proto import taktician_pb2 as tak_dot_proto_dot_taktician__pb2


class TakticianStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Analyze = channel.unary_unary(
        '/tak.proto.Taktician/Analyze',
        request_serializer=tak_dot_proto_dot_taktician__pb2.AnalyzeRequest.SerializeToString,
        response_deserializer=tak_dot_proto_dot_taktician__pb2.AnalyzeResponse.FromString,
        )


class TakticianServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Analyze(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TakticianServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Analyze': grpc.unary_unary_rpc_method_handler(
          servicer.Analyze,
          request_deserializer=tak_dot_proto_dot_taktician__pb2.AnalyzeRequest.FromString,
          response_serializer=tak_dot_proto_dot_taktician__pb2.AnalyzeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tak.proto.Taktician', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
